### ISSUE TITLE
Can't click cofirm  

### ISSUE THREAD

**Issue by duxin0817060114** [arkadiko-dao/arkadiko#103]
![image](https://user-images.githubusercontent.com/85051250/123724866-a7c52380-d8bf-11eb-9caa-98ffc6303dec.png)
Can't click cofirm

**Comment by philipdesmedt** [comment]
Thanks for reporting @duxin0817060114 - this seems to be an issue with the Stacks Web Wallet browser extension. Which version are you using?

**Comment by duxin0817060114** [comment]
Wallet version 2.11.1 , browser version   86.0.4240.198

**Comment by 314159265359879** [comment]
The web wallet issue is being tracked here https://github.com/blockstack/stacks-wallet-web/issues/934

**Comment by Macxim** [comment]
I think this can be closed for now.
Feel free to open a new issue if it happens again.
