### ISSUE TITLE
Add support for microblocks

### ISSUE THREAD

**Issue by philipdesmedt** [arkadiko-dao/arkadiko#104]
Once the microblocks APIs are live, we should implement support in Arkadiko wherever possible.

**Comment by duxin0817060114** [comment]
Is the test over yet? The wallet is empty
![image](https://user-images.githubusercontent.com/85051250/129332563-50fdf18a-4c23-4943-adb7-b52ed4bc7f27.png)

**Comment by Macxim** [comment]
Regtest is disabled, yes, if that's what you meant.

See https://twitter.com/ArkadikoFinance/status/1414621035496886277
