### ISSUE TITLE
UX Make whole input field clickable to place cursor

### ISSUE THREAD

**Issue by 314159265359879** [arkadiko-dao/arkadiko#114]
I noticed this on Vault creation (using Brave on Windows 10)
If I click in the input field anywhere on the red cross nothing happons, I expect the cursor to go to the start just as it does when you click the first bit of the field. 
![image](https://user-images.githubusercontent.com/33360391/124322151-3ddaa180-db7f-11eb-8b6b-e032f6318a3e.png)

**Comment by Macxim** [comment]
@314159265359879 Thanks for reporting, I'll look into it.

**Comment by Macxim** [comment]
@314159265359879 Should be good now, once this ☝️ is merged.
