### ISSUE TITLE
New vault: it's possible to pass the first step even with 0 DIKO

### ISSUE THREAD

**Issue by Macxim** [arkadiko-dao/arkadiko#119]
An error should be shown informing about insufficient balance.

https://user-images.githubusercontent.com/1909957/124776367-4d6b3900-df37-11eb-9483-6e191b8f14e8.mov

**Comment by philipdesmedt** [comment]
Thanks - will fix this (low prio)

**Comment by philipdesmedt** [comment]
Fixed on master.
