### ISSUE TITLE
Max button doesn't work on Withdraw Collateral dialogue

### ISSUE THREAD

**Issue by 314159265359879** [arkadiko-dao/arkadiko#123]
when withdrawing stx from a vault (Tested with Brave (latest) on Windows 10)
button/ box _light up_ but does not input the numbers.

![image](https://user-images.githubusercontent.com/33360391/124923040-5e30b300-dffa-11eb-8f9f-a68abd5f69df.png)

**Comment by 314159265359879** [comment]
there is something else on this dialogue. When I put the cursor in the text box and start typing it will not register the first or first couple of key presses. Tried again on _pay back_, _mint_ and _deposit_ dialogue which do not have that issue. perhaps it is related?

**Comment by philipdesmedt** [comment]
Thanks for reporting @314159265359879 - this has been fixed on `master`. Cannot update regtest now since smart contracts have changed significantly but will be fixed on next deployment.
