### ISSUE TITLE
input on deposit extra collateral broken

### ISSUE THREAD

**Issue by 314159265359879** [arkadiko-dao/arkadiko#124]
![image](https://user-images.githubusercontent.com/33360391/124947935-8f1be280-e010-11eb-8b79-353e0e23e41c.png)

You can press any key, for example 2 and it will look like it ignores the first keypress and then show a two on the second key press, if you press to again it will show 0.0 again. 
![image](https://user-images.githubusercontent.com/33360391/124948483-05204980-e011-11eb-855d-4dc12300e563.png)

![image](https://user-images.githubusercontent.com/33360391/124948413-f3d73d00-e010-11eb-8cf8-5a9a9ee27301.png)

clicking max makes it impossible to clear the field, and I cannot send the transaction.

Previously it was no problem to deposit extra collateral, maybe an update broke it?

**Comment by philipdesmedt** [comment]
Thanks for reporting @314159265359879 - this has been fixed on `master`. Cannot update regtest now since smart contracts have changed significantly but will be fixed on next deployment.
