### ISSUE TITLE
Remove liquidity amount should be 100% by default

### ISSUE THREAD

**Issue by nieldeckx** [arkadiko-dao/arkadiko#134]
As also indicated by Pieter, in most cases you just want to withdraw 100%.

<img width="553" alt="Screenshot 2021-07-14 at 09 27 29" src="https://user-images.githubusercontent.com/5592676/125581067-b5f46540-42f1-417e-bfb7-ae688633679a.png">

**Comment by philipdesmedt** [comment]
Fixed on master.
