### ISSUE TITLE
Error handling when adding liquidity but insufficient funds for second token

### ISSUE THREAD

**Issue by nieldeckx** [arkadiko-dao/arkadiko#135]
It's currently only possible to enter an amount or click the max button for the first token. However the wallet balance for the second token can be insufficient, see screenshot below.

Best solution would be to have an input field and max button on the second token as well.

At least we could have some education to the user that he has insufficient funds to provide liquidity.

<img width="572" alt="Screenshot 2021-07-14 at 09 31 07" src="https://user-images.githubusercontent.com/5592676/125581514-75cab1a6-648d-48c8-93a2-b442940159dc.png">

**Comment by Macxim** [comment]
This has been fixed in #276 already.
