### ISSUE TITLE
Automatically scroll to top when loading new page

### ISSUE THREAD

**Issue by nieldeckx** [arkadiko-dao/arkadiko#136]
Clicked "create vault" on this page:
<img width="1262" alt="Screenshot 2021-07-14 at 09 40 49" src="https://user-images.githubusercontent.com/5592676/125582941-2135d667-c999-46e9-b2cb-59c712970bb4.png">

The page to create a vault did not show the top of the page:
<img width="1254" alt="Screenshot 2021-07-14 at 09 41 01" src="https://user-images.githubusercontent.com/5592676/125582935-c403dac3-28a9-4003-86d5-d82b3af19cba.png">

**Comment by Macxim** [comment]
This has been annoying me for a long time as well, not sure why it happens.
It seems that the scroll position is maintained when navigating.
