### ISSUE TITLE
Fix staking APY calculations

### ISSUE THREAD

**Issue by nieldeckx** [arkadiko-dao/arkadiko#139]
Calculation should be based on total staked per pool.

<img width="1225" alt="Screenshot 2021-07-16 at 15 44 43" src="https://user-images.githubusercontent.com/5592676/125957718-2885c71e-2f4b-41c2-b892-47283166cbd4.png">

**Comment by nieldeckx** [comment]
See comments on: https://github.com/arkadiko-dao/arkadiko/issues/97

**Comment by philipdesmedt** [comment]
@nieldeckx can you fix this?
