### ISSUE TITLE
Do not close vault if all dept is paid back

### ISSUE THREAD

**Issue by nieldeckx** [arkadiko-dao/arkadiko#140]
Reason:
When a user pays back all dept, the code will try to close the vault immediately. However, if STX is stacking the vault can not be closed. So if STX is stacking it prevents the user from paying back all dept.

Closing a vault will be an explicit user action, only if all dept is paid back and no STX are stacked.

**Comment by philipdesmedt** [comment]
IMHO high prio "bug" rather than a nice to have?
