### ISSUE TITLE
Vault detail page should show if auto-payoff is on/off

### ISSUE THREAD

**Issue by nieldeckx** [arkadiko-dao/arkadiko#181]

**Comment by philipdesmedt** [comment]
@nieldeckx is this implemented?

**Comment by nieldeckx** [comment]
@philipdesmedt No, but users will need to claim pox rewards manually so this will be part of https://github.com/arkadiko-dao/arkadiko/pull/319

**Comment by philipdesmedt** [comment]
@nieldeckx got it
