### ISSUE TITLE
Transation rejected - bad nonce

### ISSUE THREAD

**Issue by seansoe** [arkadiko-dao/arkadiko#25]
Hi Arkadiko Devs,

I just did a test on regtest network. At the very beginning, everything works fine. I made a vault, and minted 400 xUSDs. Then when I clicked "Claim" Diko which needed a transactionn signed by STX web wallet. The "bad nonce" error showed. Then I switched to Swap page, tried to do swap, and the same error again. 

I don't know whether it is an Arkadiko issue or the web wallet one. The wallet is the Chrome extension which version is 2.1.1. I tried to sign out wallet and retried, still the same error. Then I tried to exit Chrome, and opened Arkadiko, not working. Now I can't issue any transaction with Arkadiko.

My wallet address is ST7QXF69DV4B5TV0GJGJFED2JBRED62BAW021447 on regtest network.

Screenshots attached. 

<img width="1229" alt="bad-nonce" src="https://user-images.githubusercontent.com/30616291/122327453-7879f280-cf60-11eb-8be9-1219c2404d2c.png">
<img width="445" alt="trans-history" src="https://user-images.githubusercontent.com/30616291/122327480-7f086a00-cf60-11eb-8fd6-38e855979d8a.png">

Best Regards,
Bo

**Comment by philipdesmedt** [comment]
Hi there! Thanks for reporting this.

It looks like this is an issue with the Stacks Web Wallet. Are you running v2.11.0? Just verifying since you said it was v2.1.1 which is an old version. If you are running v2.11.0, I will include someone from the Hiro team who maintain the wallet to see if they can chip in.

**Comment by seansoe** [comment]
Sorry I made a mistake about the version. The version of my web wallet is 2.11.1, which is the latest one.

**Comment by philipdesmedt** [comment]
OK, let me ask the Hiro team about this!

**Comment by seansoe** [comment]
I removed the web wallet and reinstalled it, then I can issue txs again.
But it showed up once more after I tried to pay back my debt, which was in the end a failed tx. Please see below:

Figure 1. I tried to pay back
<img width="593" alt="屏幕快照 2021-06-25 15 08 26" src="https://user-images.githubusercontent.com/30616291/123385686-659e9800-d5c8-11eb-9a23-d89e67c15540.png">

Figure 2 It showed a failed tx for no reason
<img width="384" alt="屏幕快照 2021-06-25 15 07 55" src="https://user-images.githubusercontent.com/30616291/123385713-6df6d300-d5c8-11eb-974a-bdcb62a746e2.png">

Then "Transation rejected - badnonce" comes up for every transaction again.

**Comment by philipdesmedt** [comment]
@seansoe can you link the transaction?

**Comment by seansoe** [comment]
The tx id is 0xdd88cc1424206aca6603c1c33db233b0943ce94149f2c48ce62be47111280214.

Thanks

**Comment by philipdesmedt** [comment]
This failed on burn indeed cause your STX are still stacked in PoX and you cannot close your vault if they are. We will make this clearer.

Not sure how that explains a bad nonce error though. I think they're two separate issues.

**Comment by markmhx** [comment]
Please let us know if you run into this nonce issue again. We resolved some nonce handling issues for the wallet a couple of weeks back, so I suspect that this instance may have gotten resolved. But we can investigate further if it crops up again!

**Comment by philipdesmedt** [comment]
@markmhx thanks for your comment here!

@seansoe let me know if this happens again. I'll close this issue in a few days.

**Comment by seansoe** [comment]
OK, I just downloaded the latest version 2.12.2, and the bad nonce error would not happen again. Good job, thanks.
So close this issue.
