### ISSUE TITLE
'Connect wallet' button unresponsive after signing out

### ISSUE THREAD

**Issue by jasperjansz** [arkadiko-dao/arkadiko#26]
Was connected before, then signed out. Button becomes unresponsive

![image](https://user-images.githubusercontent.com/25477905/122368107-5632a580-cf5d-11eb-8260-19de979b63da.png)

**Comment by philipdesmedt** [comment]
Good find! We'll fix this

**Comment by philipdesmedt** [comment]
@jasperjansz I can't replicate this, with either button (big one on Swap, nor the one in the navbar). Do you get a JS console error?

**Comment by philipdesmedt** [comment]
Closing this due to lack of response & unable to replicate
