### ISSUE TITLE
suggestion: ability to fill bottom amount field

### ISSUE THREAD

**Issue by jasperjansz** [arkadiko-dao/arkadiko#27]
Would be great if you could fill in the bottom of the two fields as well:

![image](https://user-images.githubusercontent.com/25477905/122368503-b1649800-cf5d-11eb-8eca-1ef1790d29a2.png)

**Comment by nieldeckx** [comment]
Unfortunately, the swap contract does not support this feature where the user would be able to enter an exact output amount rather than an exact input amount.
