### ISSUE TITLE
suggestion: use same label for function call as the one in UI

### ISSUE THREAD

**Issue by jasperjansz** [arkadiko-dao/arkadiko#28]
it'd be good to use the same label for the function as you use in the UI ("swap tokens" vs "swap-x-and-y")

![image](https://user-images.githubusercontent.com/25477905/122368864-fdafd800-cf5d-11eb-9330-b41c80219332.png)

**Comment by philipdesmedt** [comment]
@jasperjansz can we change the label that is show in the web wallet? We have two functions: swap-x-for-y and swap-y-for-x in the smart contracts, so not sure if we can modify this? Don't think so as it would abstract away the name of the smart contract function which could result in security issues?

**Comment by jasperjansz** [comment]
only by deploying a new contract and changing the function name unfortunately. It's not a big deal imo as the labels already pretty close
