### ISSUE TITLE
Minting post-condition is "greater than"

### ISSUE THREAD

**Issue by jasperjansz** [arkadiko-dao/arkadiko#29]
Is there a reason the post condition is set to at least 85 STX instead of at most or exactly 85 STX?

![image](https://user-images.githubusercontent.com/25477905/122369934-ee7d5a00-cf5e-11eb-9fdb-196604b8403f.png)

**Comment by philipdesmedt** [comment]
@jasperjansz will fix this, but in the past we sometimes had issues with post conditions where the exact ones would fail.. don't remember why but will fix this
