### ISSUE TITLE
"stake DIKO" balance seems incorrect

### ISSUE THREAD

**Issue by jasperjansz** [arkadiko-dao/arkadiko#30]
I have DIKO balance in the wallet, but the UI tells me I have 0 DIKO

![image](https://user-images.githubusercontent.com/25477905/122371244-02758b80-cf60-11eb-993a-be443993fc36.png)

**Comment by philipdesmedt** [comment]
Good find! We use the JavaScript `toLocaleString` function.. this rounds down to 2 decimals... will fix!

**Comment by philipdesmedt** [comment]
@jasperjansz this is fixed in https://github.com/arkadiko-dao/arkadiko/pull/74
