### ISSUE TITLE
[Refactoring] Extract and simplify repeated asserts

### ISSUE THREAD

**Issue by LNow** [arkadiko-dao/arkadiko#320]
In many places you have code like this one:
https://github.com/arkadiko-dao/arkadiko/blob/4a5eb38c19ae3881140a386bba1c20a73a6eb91e/clarity/contracts/arkadiko-freddie-v1-1.clar#L55-L58

it is repeated multiple times in multiple contracts (with different variable name in each contract).

To make code cleaner, shorter, more readable and a bit cheap to execute I would recommend to extract this logic into separate `read-only` function, and call it wherever it is needed.
```clojure
(define-read-only (is-shutdown-activated)
  (and 
     ;; (not x) is cheaper to execute than (is-eq x false)
     (not (unwrap-panic (contract-call? .arkadiko-dao get-emergency-shutdown-activated))) 
     (not (var-get freddie-shutdown-activated)) 
  ) 
)
```

**Comment by philipdesmedt** [comment]
Good improvement. Current versions are immutable (as they are deployed). 

Will put this in code guidelines once we have some.
