### ISSUE TITLE
[Refactoring] Replace `unwrap-panic` with `unwrap!` and proper error code + logic extraction

### ISSUE THREAD

**Issue by LNow** [arkadiko-dao/arkadiko#321]
https://github.com/arkadiko-dao/arkadiko/blob/4a5eb38c19ae3881140a386bba1c20a73a6eb91e/clarity/contracts/arkadiko-swap-v1-1.clar#L143

To make code consistent `unwrap-panic` should be replaced with `unwrap!` and proper error code.
Additionally, I would recommend to extract `map-get?` into separate `read-only` function to make code a bit more cleaner and cheaper.

```clojure
(define-read-only (get-pair-data (token-x principal) (token-y principal))
  (map-get? pairs-data-map { token-x: token-x, token-y: token-y })
)
```

**Comment by philipdesmedt** [comment]
Agreed. Best practice would be using `unwrap-panic` as little as possible since this makes it hard to debug (it throws `(err none)` which is annoying).

Going to put this in code guidelines
