### ISSUE TITLE
The "Not enough liquidity" button on Swap should be other color & disabled

### ISSUE THREAD

**Issue by philipdesmedt** [arkadiko-dao/arkadiko#37]

**Comment by Macxim** [comment]
Disabling buttons is not great. We should allow the button to be clicked and display an error message when somethings wrong.

**Comment by philipdesmedt** [comment]
@Macxim generally agree, but I think the UX is quite good here.. Uniswap does this as well, see screenshot

![image](https://user-images.githubusercontent.com/577420/123505252-4fdbb200-d65e-11eb-903c-ecf5102fa065.png)

**Comment by Macxim** [comment]
Yeah, I know, Sushiswap and Binance as well, among others probably. Doesn't mean it's the right thing to do. I'll investigate further and implement it next week.

**Comment by philipdesmedt** [comment]
@Macxim TBH it is cause it becomes a standard that users recognize. Even if it's "wrong" by the book

**Comment by Macxim** [comment]
Very true

**Comment by philipdesmedt** [comment]
but I'll leave it up to you - personally wouldn't spend hours researching this tho since this is not something we should differentiate on IMHO :)
