### ISSUE TITLE
When burning USDA it's not clear the user needs to have enough USDA in wallet to also pay stability fee

### ISSUE THREAD

**Issue by nieldeckx** [arkadiko-dao/arkadiko#376]
User has 630.4 USDA in wallet. Tries to pay back 630 USDA but it fails:
https://explorer.stacks.co/txid/0xc2d6612c4ebd285bd214b61a45aecc9f4380871e7c5aae1f39666a2dfc08f259?chain=mainnet

The burn function will first pay back the stability fee before burning USDA. 

Solution might be to take the stability fee into account in the UI. Instead of using 630 USDA as debt parameter, we can use 630 minus the stability fee needing to be paid.

**Comment by philipdesmedt** [comment]
@Macxim @nieldeckx imho this is fairly high prio.

Maxime, could you design something based on Niel's suggestion?

**Comment by Macxim** [comment]
Yes! Will do today.
