### ISSUE TITLE
Updated Block Height on Assets are negative

### ISSUE THREAD

**Issue by 314159265359879** [arkadiko-dao/arkadiko#378]
Should they be? (current block height is 39048)

![image](https://user-images.githubusercontent.com/33360391/143242127-6031ee7a-7a0c-41bc-a896-5f32ff70fda9.png)

**Comment by philipdesmedt** [comment]
I think this is a caching issue... we get the stacks tip height from the /v2/info endpoint and

1. oracle on-chain is updated with last block height
2. /v2/info still returns a lower tip block height

I have seen this before but not over 100 blocks.. Will monitor this but probably won't (be able to) fix.
