### ISSUE TITLE
Take into account accrued stability fees when repaying loan

### ISSUE THREAD

**Issue by Macxim** [arkadiko-dao/arkadiko#385]
Someone wants to partially pay back a USDA loan.

For example say he has a 100k debt, but has 80k USDA in wallet, he then tries to repay 80k (he inputs 80k in the form) and then what is passed to HIRO web wallet is 80k + stability fees. it will fail because he doesnt have more than 80k USDA in wallet (he put in max).

So the fix is, when you submit a number in the pay back form, it needs to take into account the accrued stability fees. So if he has 2k debt and he puts in 80k, the actual number submitted to Hiro must not be higher than 80k. So the MAX button should allow an input of 78K (taking into account 2K fees).

**Comment by philipdesmedt** [comment]
Yes - this is a high prio fix

**Comment by Macxim** [comment]
It was logged already though. Duplicate of #376.
