### ISSUE TITLE
Show Available STX balance in the top bar

### ISSUE THREAD

**Issue by 314159265359879** [arkadiko-dao/arkadiko#402]
I see the STX balance in the top bar is showing STX including those locked in PoX (A). Since that is not available for the protocol or swapping it maybe more appropriate to show available balance (B) instead, just as the Hiro Wallet does?

![image](https://user-images.githubusercontent.com/33360391/146031807-eda7ac76-5376-4c2b-bfad-5dd8ba90d63a.png)

**Comment by philipdesmedt** [comment]
That probably makes sense. Let me look at this.

**Comment by philipdesmedt** [comment]
Should be fixed
