### ISSUE TITLE
Rework Manage Vault page

### ISSUE THREAD

**Issue by philipdesmedt** [arkadiko-dao/arkadiko#437]
@Macxim add your thoughts here

- Show visualisation of stacking in cycle
- Give better estimate of when users can do certain actions
- Give more info related to Bitcoin block height
- Make clearer how to stop stacking (I don't want to stack anymore, what do I do?)
- Make clearer how to do specific actions, what it implies and most importantly, what is needed to do so (reach certain block height, wait for cycle to end, etc.)

**Comment by Macxim** [comment]
Most of this was solved in #449.
