### ISSUE TITLE
Collaterol in a cooldown cycle is discibed as stacking

### ISSUE THREAD

**Issue by 314159265359879** [arkadiko-dao/arkadiko#439]
I think this is slightly inaccurate (see screenshot) funds are **not** being stacked at the moment because the vault's collateral is in a cooldown cycle.

Would a distinction help between collateral being (a) in the _Arkadiko Stacker Contract_ **+ Stacking** or (b) in the _Arkadiko Stacking Contract_ + **in Cooldown**?

The later means I can unstack+unlock and withdraw from the stacking contract.

![image](https://user-images.githubusercontent.com/33360391/153651450-af2f936c-9d54-4f41-ae6b-b98732b8c63f.png)

**Comment by philipdesmedt** [comment]
This is great, thanks @314159265359879! We are redesigning this whole page to make it easier to use.

cc @Macxim

**Comment by philipdesmedt** [comment]
@314159265359879 do you think this is resolved after last month's redesign?
