### ISSUE TITLE
Unable to withdraw

### ISSUE THREAD

**Issue by Scotty0448** [arkadiko-dao/arkadiko#440]
I have a vault that is not stacking and debt has been fully paid off. I'd like to withdraw only some of my collateral without closing the vault but the Withdraw button is not being shown. It appears to be because of this referenced line in the code.

https://github.com/arkadiko-dao/arkadiko/blob/4cd2dc87c129bd02870d2b8166019d7491225f6b/web/components/manage-vault.tsx#L801

**Comment by philipdesmedt** [comment]
The reasoning is as follows: if you don't have any debt, but want to keep on stacking, it's better to use a stacking pool. We exist to offer USDA liquidity, and not merely as a pooling solution... but it makes sense that some people want to do this. I'll discuss with the team, or feel free to open a PR that improves this :)

**Comment by Scotty0448** [comment]
Understood. I would have just used the Withdraw Collateral & Close Vault button, but I don't want to close the vault yet because I'm still waiting for the latest stacking yield payout. There may be other reasons that someone gets into a similar situation though. I'll probably just temporarily mint a small amount so as to get the Withdraw button back for now.
