### ISSUE TITLE
Incorrect USDA value when clicking to burn max

### ISSUE THREAD

**Issue by Scotty0448** [arkadiko-dao/arkadiko#444]
In the Burn USDA dialog, clicking the Max button can result in a USDA value 1000000 times  larger than it should. Changing the burnMaxAmount function to something like the following should fix it.

```
  const burnMaxAmount = () => {
    let debtToPay = Number(outstandingDebt()) * 1000000 + Number(stabilityFee);
    if (debtToPay > state.balance['usda']) {
      debtToPay = Number(state.balance['usda']);
    }
    setUsdToBurn((debtToPay / 1000000).toFixed(6));
  };
```

**Comment by philipdesmedt** [comment]
Thanks for reporting @Scotty0448! Will fix this and deploy a new front-end
