### ISSUE TITLE
Missing button to login/connect 

### ISSUE THREAD

**Issue by 314159265359879** [arkadiko-dao/arkadiko#469]
Firefox/Chrome Windows 10

![image](https://user-images.githubusercontent.com/33360391/159370164-759d2c84-616f-410e-aed4-da1f927d88b6.png)

**Comment by 314159265359879** [comment]
I guess having it under swap also works. But I can see how I, or an other user, would still expect it in the upper right corner.

**Comment by philipdesmedt** [comment]
@Macxim

**Comment by Macxim** [comment]
Thanks, @314159265359879, will fix.
