### ISSUE TITLE
Incorrect message when depositing extra AUTO-ALEX collateral

### ISSUE THREAD

**Issue by Scotty0448** [arkadiko-dao/arkadiko#525]
When depositing extra AUTO-ALEX collateral, the info box displayed in the dialog has verbiage specific to STX being deposited.

![deposit](https://user-images.githubusercontent.com/43150624/200151659-09390eff-83a3-4141-8094-a6390ec5966d.png)

**Comment by philipdesmedt** [comment]
@Scotty0448 thanks for reporting! Will fix this

**Comment by philipdesmedt** [comment]
This is a higher prio issue now since it incorrectly sets the post conditions, need to fix

**Comment by philipdesmedt** [comment]
This is fixed. Closing this
