### ISSUE TITLE
Incorrect display of xBTC price

### ISSUE THREAD

**Issue by Scotty0448** [arkadiko-dao/arkadiko#531]
The current xBTC price displayed on a detail page for xBTC vaults needs to be adjusted by 100x.

![Screen Shot 2022-11-29 at 8 52 38 AM](https://user-images.githubusercontent.com/43150624/204579030-eed8c68c-f0cd-4c0f-b9e5-59d89cbb3023.png)

**Comment by philipdesmedt** [comment]
This is fixed
