### ISSUE TITLE
Staking: do not show 0% APY, show wallet balance, disable buttons where applicable

### ISSUE THREAD

**Issue by philipdesmedt** [arkadiko-dao/arkadiko#67]
![image](https://user-images.githubusercontent.com/577420/122689338-1819d800-d222-11eb-800a-05353877f2e9.png)

**Comment by nieldeckx** [comment]
<img width="807" alt="Screenshot 2021-06-21 at 17 15 16" src="https://user-images.githubusercontent.com/5592676/122786206-5bbd2200-d2b4-11eb-94e1-0f76cb9fd712.png">

**Comment by philipdesmedt** [comment]
The 0% APY was fixed.

The disabling of buttons and wallet balance we will do in another card where Maxime can redesign this page once we have LP token staking.
