### ISSUE TITLE
Add UI to add liquidity to pair

### ISSUE THREAD

**Issue by philipdesmedt** [arkadiko-dao/arkadiko#72]

**Comment by Macxim** [comment]
Some inspiration


![IMG_9909](https://user-images.githubusercontent.com/1909957/123523930-ff487100-d6be-11eb-82d5-06f417a1fa74.PNG)


![IMG_9908](https://user-images.githubusercontent.com/1909957/123523931-00799e00-d6bf-11eb-8fb7-59a5a5ca83d8.PNG)
![IMG_9907](https://user-images.githubusercontent.com/1909957/123523932-00799e00-d6bf-11eb-98a5-a9e473a515c0.PNG)
![IMG_9906](https://user-images.githubusercontent.com/1909957/123523935-01123480-d6bf-11eb-8598-cb6b3004b8c8.PNG)
<img width="747" alt="IMG_9904" src="https://user-images.githubusercontent.com/1909957/123523936-01aacb00-d6bf-11eb-8599-d3d52ec85921.PNG">
