### ISSUE TITLE
UI to remove liquidity from pair

### ISSUE THREAD

**Issue by philipdesmedt** [arkadiko-dao/arkadiko#73]

**Comment by Macxim** [comment]
Some inspiration:

![zjxMZAbQyLMP4mpb4f6OmRPra7VeLgHWu_d_N9-p9K5e0S8B1QBzyKdEaAyv1LohGLiXwKVoGcXqSDehULzOACm2ojSL9JiRwyBZ-DOLOSpzfwk5mtXrQZjhPu2wRDBg8ER_Y3jm](https://user-images.githubusercontent.com/1909957/123859313-66af2c80-d91c-11eb-9c82-a7c2dd54ea05.png)
![vs0mllfFUyTOqB-a4tQ0Rx-DbrUpcG71yIBI_CEX1Qe1xbXMnr-jkECYgW8PD6qW4P09zUtkaaddu35aneoBqrHwuDklK9QMZSnjSMnjNKs_mcwqNNjPUuwe6XQqy-15eO62M5nV](https://user-images.githubusercontent.com/1909957/123859316-6747c300-d91c-11eb-986c-63ad5a9e31ca.png)


![32vrqos0v3y61](https://user-images.githubusercontent.com/1909957/123859450-92caad80-d91c-11eb-876e-eead59da6871.png)
![assets--MKsPzOy-nKwR8hj91rg--MKsXgiqbQkPUi2p_Uq_--MKsZ7bL2RsELrWRMpqg-7](https://user-images.githubusercontent.com/1909957/123859547-b261d600-d91c-11eb-99ab-73f868714e8c.jpg)
![1-1](https://user-images.githubusercontent.com/1909957/123859689-dc1afd00-d91c-11eb-9d9e-20d120016457.png)

**Comment by Macxim** [comment]
Thoughts on this? 
@philipdesmedt @nieldeckx

Feedback welcome, as usual.

This is obviously highly inspired from the screenshot above. The slider thingy isn't final (this is the native HTML element) because I think it would be better to use some external component such as https://chakra-ui.com/docs/form/slider, or even remove the slider and go with a simple input field.

<img width="550" alt="Screen Shot 2021-07-05 at 2 53 31 PM" src="https://user-images.githubusercontent.com/1909957/124482886-a7d29100-dda1-11eb-87c5-fddd931bcd81.png">

**Comment by philipdesmedt** [comment]
@Macxim looks great! Two things:

- I'm not sure what the added complexity & file size of Chakra UI is.. there is nothing inside of Tailwind we can just use natively together with the HTML element?
- We don't need the Approve button (this is some ETH thing where you approve IIRC). We just need a remove TX signing/confirmation button

**Comment by Macxim** [comment]
@philipdesmedt First thing that come to my mind is hiding the native `<input type="range">` and doing everything with simple `<div>s`. 😄

**Comment by nieldeckx** [comment]
For me there is no added value of having a slider. In most cases you just remove 100% of liquidity, and to cover the other cases an input field is easier to use imo. :)

**Comment by philipdesmedt** [comment]
All right, let's remove the slider then?

**Comment by Macxim** [comment]
Just when I'm done doing it with Tailwind 😂 

<img width="553" alt="Screen Shot 2021-07-05 at 4 08 01 PM" src="https://user-images.githubusercontent.com/1909957/124491539-4e6f5f80-ddab-11eb-9148-fa80ca123682.png">

I don't mind removing it either.
