### ISSUE TITLE
trading address

### ISSUE THREAD

**Issue by duxin0817060114** [arkadiko-dao/arkadiko#78]
After the successful SWAP, can the block trading address be displayed?
![image](https://user-images.githubusercontent.com/85051250/122867006-7696a180-d35b-11eb-8b27-e915a9276bf4.png)

**Comment by GAD2511** [comment]
Instead of the block, I suggest tx id be displayed

**Comment by duxin0817060114** [comment]
Good idea

**Comment by philipdesmedt** [comment]
Thanks! We will add a link to the transaction in the popup :)

**Comment by philipdesmedt** [comment]
This has been implemented and will be released soon.
