### ISSUE TITLE
UI show failed transactions

### ISSUE THREAD

**Issue by 314159265359879** [arkadiko-dao/arkadiko#80]
orange bullit is pending
green is succesful
red for failed?
![show-failed_transactions_in_list_with_red_bullit](https://user-images.githubusercontent.com/33360391/122996238-eb44fc80-d3aa-11eb-878d-472953299b6c.png)

**Comment by philipdesmedt** [comment]
Good idea. I'll add these!

**Comment by philipdesmedt** [comment]
Implemented - will be released in new build
