### ISSUE TITLE
Always show relevant balances

### ISSUE THREAD

**Issue by 314159265359879** [arkadiko-dao/arkadiko#81]
For example under or above the navbar show: xusd-, stx-, xstx-, diko-, stdiko-balance (and a button to hide it)

This could alleviate the need on other screen to show the balance. Some exchanges do this for the active trading pair and some additional balances such as BTC. I think it helps with the overall overview and to track changes after transactions are confirmed.

**Comment by philipdesmedt** [comment]
@Macxim thoughts? I think this is a good idea. This way we can eliminate the balances on the Mint/Vaults page and show them always in a collapsable menu.

**Comment by Macxim** [comment]
Agree, having a quick overview of your overall balance would be cool.

@314159265359879 Do you have any real life example? Any screenshots?

**Comment by 314159265359879** [comment]
@Macxim  Here are two examples old (A), and evolved version (B) on Bitstamp tradeview (see top middle). Here the distinction is made between balance and available (balance). For Arkadiko only showing available balance likely suffices. Because (unavailable) stacked stx will show as available xstx and the same goes for DIKO and stDIKO. 

A.
![image a bitstamp balances shown at top](https://user-images.githubusercontent.com/33360391/123144157-aaf18700-d45b-11eb-96f1-6c229d86981d.jpg)

B.
![image a bitstamp balances shown at top b](https://user-images.githubusercontent.com/33360391/123144212-bcd32a00-d45b-11eb-8653-8802f1578c77.jpg)
